apiVersion: v1
kind: Service
metadata:
  name: phpinfo
  labels:
    app: phpinfo
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: phpinfo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpinfo
  labels:
    app: phpinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpinfo
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: phpinfo
        tier: frontend
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/phpinfo
        name: phpinfo
        ports:
        - containerPort: 8080
          name: phpinfo
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: phpinfo
  name: phpinfo
  namespace: myproject
spec:
  host: phpinfo.minishift.local
  to:
    kind: Service
    name: phpinfo
    weight: 100
  wildcardPolicy: None
